<a href="https://colab.research.google.com/github/pranavdighade123/Data-Preprocessing-Practicals-/blob/main/DP_Practical05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Title: Implement normalization on data.


In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
myarray = np.array([12,52,85,99,62,354,75])
print(myarray)

[ 12  52  85  99  62 354  75]


In [ ]:
a=np.random.random((1,4))
a=a*20
print(a)

[[16.90015589 16.21946436 14.55108534  8.50662238]]


In [ ]:
normalization=preprocessing.normalize([myarray])
print(normalization)

[[0.03051361 0.13222566 0.2161381  0.25173731 0.15765367 0.90015161
  0.19071009]]


In [ ]:
normalization2=preprocessing.normalize(a)
print(normalization2)        

[[0.58563198 0.56204434 0.50423091 0.29477539]]
