<a href="https://colab.research.google.com/github/pranavdighade123/Data-Preprocessing-Practicals-/blob/main/DP_Practical03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Title: Perform the Categorization of dataset


In [ ]:
import sklearn as sk
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving SAheart.csv to SAheart.csv


Binary Classification 

In [ ]:
heart = pd.read_csv("SAheart.csv")
print(heart.head())
y = heart.iloc[:,9]
X = heart.iloc[:,:9]


   sbp  tobacco   ldl  adipo1ty  famhist  typea  obe1ty  alcohol  age  chd
0  160    12.00  5.73     23.11        1     49   25.30    97.20   52    1
1  144     0.01  4.41     28.61        0     55   28.87     2.06   63    1
2  118     0.08  3.48     32.28        1     52   29.14     3.81   46    0
3  170     7.50  6.41     38.03        1     51   31.99    24.26   58    1
4  134    13.60  3.50     27.78        1     60   25.99    57.34   49    1


Logistic Regression

In [ ]:
from numpy import array
LR = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X, y)
LR.predict(X.iloc[460:,:])
round(LR.score(X,y), 4)
array([1,1])

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 1])

Support Vector Machine

In [ ]:
SVM = svm.LinearSVC()
SVM.fit(X, y)
SVM.predict(X.iloc[460:,:])
round(SVM.score(X,y), 4)
array([0, 1])


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


array([0, 1])

Random Forest

In [ ]:
RF = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
RF.fit(X, y)
RF.predict(X.iloc[460:,:])
round(RF.score(X,y), 4)
0.7338


0.7338

Neural Network

In [ ]:
NN = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
NN.fit(X, y)
NN.predict(X.iloc[460:,:])
round(NN.score(X,y), 4)
0.6537


0.6537

Multi-Class Classification 

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving vowel.test.csv to vowel.test.csv


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving vowel.train.csv to vowel.train.csv


In [ ]:
vowel_train = pd.read_csv("vowel.train.csv")
vowel_test = pd.read_csv("vowel.train.csv")
print(vowel_train.head())
y_tr = vowel_train.iloc[:,0]
X_tr = vowel_train.iloc[:,1:]
y_test = vowel_test.iloc[:,0]
X_test = vowel_test.iloc[:,1:]

   row.names  y    x.1    x.2    x.3    x.4    x.5    x.6    x.7    x.8  \
0          1  1 -3.639  0.418 -0.670  1.779 -0.168  1.627 -0.388  0.529   
1          2  2 -3.327  0.496 -0.694  1.365 -0.265  1.933 -0.363  0.510   
2          3  3 -2.120  0.894 -1.576  0.147 -0.707  1.559 -0.579  0.676   
3          4  4 -2.287  1.809 -1.498  1.012 -1.053  1.060 -0.567  0.235   
4          5  5 -2.598  1.938 -0.846  1.062 -1.633  0.764  0.394 -0.150   

     x.9   x.10  
0 -0.874 -0.814  
1 -0.621 -0.488  
2 -0.809 -0.049  
3 -0.091 -0.795  
4  0.277 -0.396  


In [ ]:
y_tr = vowel_train.iloc[:,0]
X_tr = vowel_train.iloc[:,1:]
y_test = vowel_test.iloc[:,0]
X_test = vowel_test.iloc[:,1:]


ogistic Regression of vowel dataset:

In [ ]:
LR = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial').fit(X_tr,
y_tr)
LR.predict(X_test)
round(LR.score(X_test,y_test), 4)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5966

Support Vector Machine of vowel dataset:

In [ ]:
SVM = svm.SVC(decision_function_shape="ovo").fit(X_tr, y_tr)
SVM.predict(X_test)
round(SVM.score(X_test, y_test), 4)

1.0

Random Forest of vowel dataset: 

In [ ]:
RF = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0).fit(X_tr,
y_tr)
RF.predict(X_test)
round(RF.score(X_test, y_test), 4)

0.9943

Neural Network of vowel dataset: 

In [ ]:
NN = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(150, 10),
random_state=1).fit(X_tr, y_tr)
NN.predict(X_test)
round(NN.score(X_test, y_test), 4)

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


0.1136

Logistic Regression: 59.6


Support Vector Machine: 1


Random Forest: 99.4


Neural Network: 11.3